spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tQTtRVk51LwfqebNhxB
      secret-key: Ya3P7HW7hx8aLgUAOUu3LqLPyKyHpP
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulimall-linke

  application:
    name: gulimall-third-party

server:
  port: 21000
